package net.projecteuler;

/*
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle
 * number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */
public class Problem0012 {

  public static void main(String[] args) {

    int t = 0;
    int dHarf = 500 / 2;
    int max = 0;
    int gt = 0;
    for (int i = 1; i < 50000; i++) {

      t = t + i;

      // System.out.print(t + " : ");

      int dCount = 0;
      for (int j = 1; j <= t; j++) {

        if (t % j == 0) {
          int l = t / j;

          if (l < j) {
            break;
          } else {
            dCount++;
          }

          // System.out.print(j + " x " + l + ",");

        }

      }

      if (max < dCount) {
        max = dCount;
        gt = t;
      }
      if (dCount > dHarf) {
        break;
      }
    }

    System.out.println(max + " : " + gt);
  }

}
